// Generated by gencpp from file juk_msg/juk_control_dji_msg.msg
// DO NOT EDIT!


#ifndef JUK_MSG_MESSAGE_JUK_CONTROL_DJI_MSG_H
#define JUK_MSG_MESSAGE_JUK_CONTROL_DJI_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace juk_msg
{
template <class ContainerAllocator>
struct juk_control_dji_msg_
{
  typedef juk_control_dji_msg_<ContainerAllocator> Type;

  juk_control_dji_msg_()
    : flag(0)
    , data_x(0.0)
    , data_y(0.0)
    , data_z(0.0)
    , course(0.0)  {
    }
  juk_control_dji_msg_(const ContainerAllocator& _alloc)
    : flag(0)
    , data_x(0.0)
    , data_y(0.0)
    , data_z(0.0)
    , course(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef float _data_x_type;
  _data_x_type data_x;

   typedef float _data_y_type;
  _data_y_type data_y;

   typedef float _data_z_type;
  _data_z_type data_z;

   typedef float _course_type;
  _course_type course;



  enum {
    FLAG_VELOCITY = 1u,
    FLAG_ANGLES = 2u,
    FLAG_BREAK = 3u,
    FLAB_NOTHING = 4u,
  };


  typedef boost::shared_ptr< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> const> ConstPtr;

}; // struct juk_control_dji_msg_

typedef ::juk_msg::juk_control_dji_msg_<std::allocator<void> > juk_control_dji_msg;

typedef boost::shared_ptr< ::juk_msg::juk_control_dji_msg > juk_control_dji_msgPtr;
typedef boost::shared_ptr< ::juk_msg::juk_control_dji_msg const> juk_control_dji_msgConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::juk_msg::juk_control_dji_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace juk_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'juk_msg': ['/home/ubuntu/catkin_ws/src/juk-msg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abe0ee84b4a03285cfba0c7476d4adad";
  }

  static const char* value(const ::juk_msg::juk_control_dji_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabe0ee84b4a03285ULL;
  static const uint64_t static_value2 = 0xcfba0c7476d4adadULL;
};

template<class ContainerAllocator>
struct DataType< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "juk_msg/juk_control_dji_msg";
  }

  static const char* value(const ::juk_msg::juk_control_dji_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 FLAG_VELOCITY = 1\n"
"uint8 FLAG_ANGLES = 2\n"
"uint8 FLAG_BREAK = 3\n"
"uint8 FLAB_NOTHING = 4\n"
"\n"
"uint8 flag\n"
"float32 data_x\n"
"float32 data_y\n"
"float32 data_z\n"
"float32 course\n"
;
  }

  static const char* value(const ::juk_msg::juk_control_dji_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
      stream.next(m.data_x);
      stream.next(m.data_y);
      stream.next(m.data_z);
      stream.next(m.course);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct juk_control_dji_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::juk_msg::juk_control_dji_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::juk_msg::juk_control_dji_msg_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "data_x: ";
    Printer<float>::stream(s, indent + "  ", v.data_x);
    s << indent << "data_y: ";
    Printer<float>::stream(s, indent + "  ", v.data_y);
    s << indent << "data_z: ";
    Printer<float>::stream(s, indent + "  ", v.data_z);
    s << indent << "course: ";
    Printer<float>::stream(s, indent + "  ", v.course);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUK_MSG_MESSAGE_JUK_CONTROL_DJI_MSG_H
