// Generated by gencpp from file juk_msg/juk_aruco_module_data.msg
// DO NOT EDIT!


#ifndef JUK_MSG_MESSAGE_JUK_ARUCO_MODULE_DATA_H
#define JUK_MSG_MESSAGE_JUK_ARUCO_MODULE_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace juk_msg
{
template <class ContainerAllocator>
struct juk_aruco_module_data_
{
  typedef juk_aruco_module_data_<ContainerAllocator> Type;

  juk_aruco_module_data_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , course(0.0)  {
    }
  juk_aruco_module_data_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , course(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _course_type;
  _course_type course;





  typedef boost::shared_ptr< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> const> ConstPtr;

}; // struct juk_aruco_module_data_

typedef ::juk_msg::juk_aruco_module_data_<std::allocator<void> > juk_aruco_module_data;

typedef boost::shared_ptr< ::juk_msg::juk_aruco_module_data > juk_aruco_module_dataPtr;
typedef boost::shared_ptr< ::juk_msg::juk_aruco_module_data const> juk_aruco_module_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::juk_msg::juk_aruco_module_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace juk_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'juk_msg': ['/home/pi/catkin_ws/src/juk_msg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d82f5957f77dc9495d5600f402914f6";
  }

  static const char* value(const ::juk_msg::juk_aruco_module_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d82f5957f77dc94ULL;
  static const uint64_t static_value2 = 0x95d5600f402914f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "juk_msg/juk_aruco_module_data";
  }

  static const char* value(const ::juk_msg::juk_aruco_module_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 course\n\
";
  }

  static const char* value(const ::juk_msg::juk_aruco_module_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.course);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct juk_aruco_module_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::juk_msg::juk_aruco_module_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::juk_msg::juk_aruco_module_data_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "course: ";
    Printer<double>::stream(s, indent + "  ", v.course);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUK_MSG_MESSAGE_JUK_ARUCO_MODULE_DATA_H
